print("Let's play Mad Libs for Homework 1")
print("Type one word responses to the following:\n")
proper_name = input("proper_name ==> ")
print(proper_name)
print()
adj1 = input("adjective ==> ")
print(adj1)
print()
noun1 = input("noun ==> ")
print(noun1)
print()
verb1 = input("verb ==> ")
print(verb1)
print()
verb2 = input("verb ==> ")
print(verb2)
print()
noun2 = input("noun ==> ")
print(noun2)
print()
emotion1 = input("emotion ==> ")
print(emotion1)
print()
verb3 = input("verb ==> ")
print(verb3)
print()
noun3 = input("noun ==> ")
print(noun3)
print()
season = input("season ==> ")
print(season)
print()
adj2 = input("adjective ==> ")
print(adj2)
print()
emotion2 = input("emotion ==> ")
print(emotion2)
print()
team_name = input("team-name ==> ")
print(team_name)
print()
noun4 = input("noun ==> ")
print(noun4)
print()
adj3 = input("adjective ==> ")
print(adj3)
print()
print("Here is your Mad Lib...")
print()
print("Good morning ", proper_name, "!", sep = "")
print()
print("This will be a/an ", adj1, " ", noun1, "! Are you ", verb1, " forward to it?", sep = "")
print("You will ", verb2, " a lot of ", noun2, " and feel ", emotion1, " when you do.", sep = "")
print("If you do not, you will ", verb3, " this ", noun3, ".", sep = "")
print()
print("This ", season, " was ", adj2, ". Were you ", emotion2, " when ", team_name, " won the ", noun4, "?", sep = "")
print()
print("Have a/an ", adj3, " day!", sep = "")